### ISSUE TITLE
Can we switch the license to MIT or BSD?

### ISSUE THREAD

**Issue by mjuric** [dirac-institute/AXS#14]
@ctslater @zecevicp -- do we have anything in the codebase that's keeping us on GPLv3? It would be better to license our modifications under MIT or BSD.

**Comment by zecevicp** [comment]
I don't see a reason not to switch to MIT.

**Comment by mjuric** [comment]
@ctslater ?

**Comment by ctslater** [comment]
Sounds good to me. Not sure I have a preference between MIT and BSD, I think either would be fine.

**Comment by mjuric** [comment]
I'll use BSD3, to be consistent with astropy.
