### ISSUE TITLE
Add a convenience for list_tables() to list 'table_id' only

### ISSUE THREAD

**Issue by bsipocz** [dirac-institute/AXS#2]
It would be very convenient to avoid the need for looping to get quick list of catalogues available.

**Comment by zecevicp** [comment]
I added the `list_table_names` method to AxsCatalog. To apply the change, you can simply replace the existing catalog.py file.

Doing that, I found a bug in AxsUtilities package where table name was returned for both ID and name fields. I fixed that too. However, AxsUtilities jar needs to be rebuilt to apply that change.

I will close the issue. If something doesn't work for you, please reopen it.
